name: "Code Style"

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: codestyle-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codestyle:
    name: codestyle
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[all]
        python -m pip install pydocstyle pycodestyle prospector pylint pyflakes bandit
    - name: Run pycodestyle
      run: pycodestyle --statistics astropop
    - name: Run pydocstyle
      run: pydocstyle astropop
    - name: Run prospector
      run: prospector -w pyflakes -w bandit --doc-warnings -F astropop

  codestyle_pull_request:
    name: codestyle-pull-request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: technote-space/get-diff-action@v6
      with:
        PATTERNS: |
          astropop/**/*.py
          tests/*.py
    - name: Print DIFF
      run: |
        echo "GIT_DIFF: ${{ env.GIT_DIFF }}"
        echo "GIT_DIFF_FILTERED: ${{ env.GIT_DIFF_FILTERED }}"

    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pycodestyle pydocstyle prospector pylint pyflakes bandit
        python -m pip install .[all]
    - name: Run pycodestyle
      run: pycodestyle --statistics ${{ env.GIT_DIFF_FILTERED}}
      if: env.GIT_DIFF_FILTERED
    - name: Run pydocstyle
      continue-on-error: true
      run: pydocstyle ${{ env.GIT_DIFF_FILTERED}}
      if: env.GIT_DIFF_FILTERED
    - name: Run prospector
      continue-on-error: true
      run: prospector -w pyflakes -w bandit -F --no-autodetect --doc-warnings ${{ env.GIT_DIFF_FILTERED}}
      if: env.GIT_DIFF_FILTERED
